### ISSUE TITLE
Fehler gefunden!

### ISSUE THREAD

**Issue by Yetam42** [TornaxO7/Chemic---Notes#2]
# Welche Seite?

Beim Thema Polykondensation auf Seite 16 
# Wo genau?
Du hast glaub nen Fehler bei der Strukturformel von Perlon. Es müsste glaub NH-CO-(CH2)5 sein und nicht NH-(CH2)5-CO 
Ich hoffe mal du verstehst was ich mein

**Comment by TornaxO7** [comment]
Sollte nun gefixt sein. Danke für die Info! :+1:
